### ISSUE TITLE
How add python external libraries ?

### ISSUE THREAD

**Issue by luancaarvalho** [A3Data/pyspark-notebook-helm#12]
Hello ! 

How can I add python libraries to my notebook ? Do I have to run spark with a custom image carrying these libraries?

Thank you !

**Comment by maylatt** [comment]
Hello @luancaarvalho!

You can just run `!pip install <package>` in your notebook or customize the jupyter/pyspark-notebook image.

Below is an example of the Dockerfile for a custom image.

```Dockerfile
FROM jupyter/pyspark-notebook:spark-3.1.2

USER root

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
```
In this case you must update the properties `image.repository` and `image.tag` in your values.yaml file.

**Comment by luancaarvalho** [comment]
Thank you a lot, that's very useful !
